# Generated by Django 5.2.1 on 2025-06-10 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_agregar_doctorform_delete_admin_delete_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buscar_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('historia_clinica', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Agregar_DoctorForm',
        ),
        migrations.RemoveField(
            model_name='agregar_paciente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='agregar_paciente',
            name='fecha_salida',
        ),
        migrations.AlterField(
            model_name='agregar_paciente',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agregar_paciente',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente'),
        ),
    ]
