# Generated by Django 5.2.1 on 2025-06-11 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_agregar_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.doctor'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.paciente'),
        ),
    ]
