# Generated by Django 5.2.1 on 2025-06-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_turno_doctor_alter_turno_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agregar_paciente',
            options={},
        ),
        migrations.AlterField(
            model_name='agregar_paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
